server:
  port: 8080
  error:
    path: /error
  servlet:
    context-path: /chapter02
    session-timeout : 30m
  tomcat:
    uri-encoding: utf-8
    max-threads : 500
    basedir:
      /home/sang/tmp